### ISSUE TITLE
QAF 2.1.13 breaks multi device teardown

### ISSUE THREAD

**Issue by zbergus** [Project-Quantum/Quantum#49]
I assume that it is due to the following change: https://github.com/qmetry/qaf/issues/131, when multiple devices are open and a teardown occurs, the first device closes but a null pointer exception is thrown for the second device

`[ ]: Executing quit parameters: {} 
[ ]: Executing close parameters: {} 
[ ]: command: close[ param-1: {}] Result: null 
[ ]: command: quit[ param-1: {}] Result: null 
[ ]: UI-driver tear down complete... 
[ ]: java.lang.NullPointerException 
[ ]: Executing screenshot parameters: {} 

java.lang.NullPointerException
	at com.qmetry.qaf.automation.core.QAFTestBase.tearDown(QAFTestBase.java:191)
	at com.qmetry.qaf.automation.ui.AbstractTestBase.tearDown(AbstractTestBase.java:106)
	at com.qmetry.qaf.automation.ui.AbstractTestCase.tearDownPrrallelThreads(AbstractTestCase.java:95)
	at com.qmetry.qaf.automation.ui.AbstractTestCase.afterTest(AbstractTestCase.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:1008)
	at org.testng.TestRunner.run(TestRunner.java:639)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Preparing For Shut Down...
Preparing For Shut Down...
Thread-0: UI-driver tear down complete... 
Exception in thread "Thread-0" java.lang.NullPointerException
	at com.qmetry.qaf.automation.core.QAFTestBase.tearDown(QAFTestBase.java:191)
	at com.qmetry.qaf.automation.core.TestBaseProvider.stopAll(TestBaseProvider.java:69)
	at com.qmetry.qaf.automation.core.TestBaseProvider$1.run(TestBaseProvider.java:97)

Process finished with exit code 0`

**Comment by kulin24** [comment]
Can you please elaborate on when this happens and are you using the latest version of Quantum?

**Comment by zbergus** [comment]
A feature which seems to have been added about a year ago allows for multiple devices to be open in the same test (not a parallel test) such as for sending SMS or calling each other. This feature is very helpful for our needs however when upgrading to qaf 2.1.13 the null pointer exception above occurs on the teardown as soon as it is done tearring down the first device driver

Below are the versions I am using:
<qaf.version>2.1.13</qaf.version>
<qafsupport.version>2.1.13</qafsupport.version>
<quantum.version>1.14</quantum.version>

**Comment by kulin24** [comment]
Okay, I will try and reproduce this issue. Thanks for the details.

**Comment by kulin24** [comment]
Fixed in the QAF version
