### ISSUE TITLE
Check for file existence before opening (failureReasons.json)

### ISSUE THREAD

**Issue by davidreedme** [Project-Quantum/Quantum#54]
When this file does not exist, other exceptions are masked by this framework error. If failureReasons.json doesn't exist, it should be skipped instead of failing.

`java.io.FileNotFoundException: File 'src\main\resources\failureReasons.json' does not exist
at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:292)
at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1765)
at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1800)
at com.quantum.listeners.QuantumReportiumListener.findFailureReason(QuantumReportiumListener.java:435)
at com.quantum.listeners.QuantumReportiumListener.onTestFailure(QuantumReportiumListener.java:167)
at com.customer.utility.CustomQuantumListener.onTestFailure(CustomQuantumListener.java:58)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1716)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
at org.testng.TestRunner.privateRun(TestRunner.java:781)
at org.testng.TestRunner.run(TestRunner.java:635)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`

**Comment by kulin24** [comment]
Thanks David, this will be fixed in the next release soon.

**Comment by kulin24** [comment]
Fixed this issue.
