### ISSUE TITLE
Check array bounds for mismatch before using other indexes (QuantumReportiumListener.java)

### ISSUE THREAD

**Issue by davidreedme** [Project-Quantum/Quantum#55]
In QuantumReportiumListener.java (line 370), the iterator is based on paramNames[], but the index is then reused to access elements of actualArgs[] without a guarantee that matching elements exist causing an out of bounds exception without explanation of the configuration mismatch.

`java.lang.ArrayIndexOutOfBoundsException: 2
at .Then I verify "SOME_TEXT" text is displayed with the format "\d{2}/\d{2}/\d{4}"(src/main/resources/scenarios/CUSTOM_TEST.feature:1981)
at com.quantum.listeners.QuantumReportiumListener.getProcessStepDescription(QuantumReportiumListener.java:377)
at com.quantum.listeners.QuantumReportiumListener.beforExecute(QuantumReportiumListener.java:117)
at com.qmetry.qaf.automation.step.BaseTestStep.beforExecute(BaseTestStep.java:180)
at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:146)
at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:173)
at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:225)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`

**Comment by ksitwala-perfecto** [comment]
Please share the step used in the scenario and the step definition used to reproduce this issue on my end.

**Comment by kulin24** [comment]
This was an issue when there are parameter values containing curly braces. Fixed this with a customised regex to evaluate the parameters that needed to be replaced in the steps for reporting.
This issue is fixed in the pre-release version 1.19-RC.
https://github.com/Project-Quantum/Quantum/releases/tag/1.19-RC
